---
- name: www.domain.com setup
  hosts: www.domain.com

  vars_files:
    - ../group_vars/domain.com.yml
    - ../group_vars/global.vars.yml

  tasks:

  - include: "{{ item }}"
    with_items:
      - std-logdir.yml
      - std-backup.yml
      - std-checkhttps.yml
      - std-letsencrypt.yml
      - std-monit.yml
      - std-mysql.yml
      - std-nginx.yml
      - std-pkgs.yml
      - std-ppaphp.yml
      - std-users.yml

