  - name: Set MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'
    become: true
  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
    become: true
  - name: Install MySQL
    apt: name={{item}} state=installed
    with_items:
      - mysql-server
      - mysql-client
    become: true

