  - name: Copy checksslexpire.sh script to server
    get_url: url=https://github.com/jurinva/checkhttps/raw/master/checkhttps.sh dest={{siterootdir | quote}}/backup mode=a+x
    become: true
  - name: Set artisan
    replace: dest={{siterootdir | quote}}/backup/checksslexpire.sh regexp=SITE replace={{ledomains | join(' ')}}
    become: true
  - name: Create checkhttps cron.d task
    - cron: name=checkhttps minute=0 hour=0 user=root job="{{siterootdir | quote}}/backup/checkhttps.sh" cron_file=checkhttps
    become: true